version: '3.9'

services:
  postgres:
    image: postgres:16-alpine   # легче и безопаснее чем latest
    container_name: tasktracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tasktracker
      POSTGRES_PASSWORD: tasktracker
      POSTGRES_DB: tasktracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tasktracker-network

  redis:
    image: redis:7-alpine
    container_name: tasktracker-redis
    restart: unless-stopped
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - tasktracker-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasktracker-api
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://tasktracker:tasktracker@postgres:5432/tasktracker
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - tasktracker-network

volumes:
  postgres_data:
  redis_data:

networks:
  tasktracker-network:
    driver: bridge